services:
  filemaker-server:
    platform: linux/amd64
    container_name: filemaker-server
    image: fmsdocker:config
    #build: .
    privileged: true
    ports:
      - "80:80"
      - "443:443"
      - "2399:2399"
      - "5003:5003"
    volumes:
      # for a new database set <volume name>:"/opt/FileMaker/FileMaker Server/Data"
      # to import existing databases set <data path>:"/opt/FileMaker/FileMaker Server/Data"
      - "<name or path>:/opt/FileMaker/FileMaker Server/Data"
      - "<name or path>:/opt/FileMaker_Backup"
    restart: "unless-stopped"